name: mpet-splitter
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - scikit-image
  - pip:
    - nibabel
    - pydicom